import { ISSUE_STATUS, ISSUE_TYPE } from '../domain/types.js'

/**
 * 13 civic issues — canonical seed for FAKE-OLD mode (ROUTING_DEMO_ISSUES).
 * summary — для карточки; description — полный текст для деталей.
 * institution, labels — метаданные.
 */
export const ROUTING_DEMO_ISSUES = Object.freeze([
  {
    id: 'DE-001',
    status: ISSUE_STATUS.PUBLISHED,
    type: ISSUE_TYPE.INCIDENT,
    labels: ['district', 'safety'],
    title: { et: 'Pensionide indekseerimine ja tegelikud kulud', ru: 'Пенсионная индексация и реальные расходы', en: 'Pension indexation and real expenses' },
    summary: { et: 'Pension tõusis, kuid kommunaalid ja ravimid kallinesid. Palun selgitada indekseerimise arvutust.', ru: 'Пенсия выросла, но выросли коммунальные и лекарства. Прошу разъяснить учёт реальных расходов.', en: 'Pension increased but utilities and medicine costs rose. Request for clarification on real expenses in indexation.' },
    description: { et: 'Sain teate pensioni tõusust, kuid samas tõusid kommunaalmaksud ja ravimite hind. Ametlikes teadetes räägitakse pensionäride heaolu kasvust, kuid minu puhul on tegelik ostujõud langenud. Palun selgitada, kas indekseerimise arvutuses arvestatakse põhiteenuste tegelikke kulusid.', ru: 'Я получила уведомление о повышении пенсии, но при этом выросли коммунальные платежи и стоимость лекарств. В официальных сообщениях говорится о росте благосостояния пенсионеров, но в моём случае фактическая покупательная способность снизилась. Прошу разъяснить, учитываются ли реальные расходы на базовые услуги при расчёте индексации.', en: 'I received notice of a pension increase, but utility bills and medicine costs also rose. Official statements speak of pensioners\' improved welfare, yet my actual purchasing power has decreased. Please clarify whether real expenses on basic services are taken into account when calculating indexation.' },
    institution: { et: 'Sotsiaalkindlustusamet', ru: 'Sotsiaalkindlustusamet', en: 'Social Insurance Board' },
    created_at: '2025-01-15T10:00:00Z',
    geo: {
      district: 'Kesklinn',
      settlement: 'Tallinn',
      region: 'Harju maakond',
      country: 'Eesti',
      postal_code: '10111',
      lat: 59.437,
      lon: 24.753,
    },
  },
  {
    id: 'DE-002',
    status: ISSUE_STATUS.NEW,
    type: ISSUE_TYPE.INCIDENT,
    labels: ['district'],
    title: { et: 'Üleminek eestikeelsele õppele', ru: 'Переход на обучение на эстонском', en: 'Transition to Estonian-language education' },
    summary: { et: 'Laps 4. klassis, ained eesti keeles, aga keeletase klassil erinev. Palju ei tule programmiga toime.', ru: 'Ребёнок в 4 классе, предметы на эстонском, но уровень языка в классе разный. Многие не справляются с программой.', en: 'Child in 4th grade, subjects taught in Estonian, but language levels in class vary. Many struggle with the curriculum.' },
    description: { et: 'Minu laps õpib 4. klassis. Ained õpetatakse eesti keeles, kuid keeletase klassis on erinev. Aasta lõpuks ei tule märkimisväärne osa õpilasi programmiga toime. Palun teavitada, millised konkreetsed tugimeetmed on ette nähtud lastele, kes ei ole saavutanud vajalikku keeletaset.', ru: 'Мой ребёнок учится в 4 классе. Предметы преподаются на эстонском языке, но уровень владения языком у класса разный. По итогам года значительная часть учеников не справляется с программой. Прошу сообщить, какие конкретные механизмы поддержки предусмотрены для детей, которые не достигли необходимого языкового уровня.', en: 'My child is in 4th grade. Subjects are taught in Estonian, but language proficiency varies across the class. By year end, a significant share of pupils struggle with the programme. Please inform what specific support mechanisms are in place for children who have not reached the required language level.' },
    institution: { et: 'Haridus- ja Teadusministeerium', ru: 'Haridus- ja Teadusministeerium', en: 'Ministry of Education and Research' },
    created_at: '2025-01-18T14:30:00Z',
    original_locale: ['ru'],
  },
  {
    id: 'DE-003',
    status: ISSUE_STATUS.IN_REVIEW,
    type: ISSUE_TYPE.INCIDENT,
    labels: ['district', 'waste'],
    title: { et: 'Metoodilised materjalid', ru: 'Методические материалы', en: 'Teaching materials' },
    summary: { et: 'Keele-reform nõuab õpetamist eesti keeles, kuid kohandatud õpikuid pole piisavalt.', ru: 'Языковая реформа обязывает преподавать на эстонском, но адаптированных учебников недостаточно.', en: 'Language reform requires teaching in Estonian, but adapted textbooks are insufficient.' },
    description: { et: 'Keele-reformi raames peame õpetama ainet eesti keeles, kuid valmis kohandatud õpikuid pole piisavalt. Palun anda tsentraliseeritud materjale või rahastus metoodikate väljatöötamiseks, kuna õpetajate koormus ületab normatiivi.', ru: 'В рамках языковой реформы мы обязаны преподавать предмет на эстонском, но готовых адаптированных учебников недостаточно. Прошу предоставить централизованные материалы или финансирование на разработку методик, поскольку нагрузка на учителей превышает норматив.', en: 'Under the language reform we must teach the subject in Estonian, but there are not enough adapted textbooks. Please provide centralised materials or funding for methodology development, as teacher workload exceeds the norm.' },
    institution: { et: 'Kohalik omavalitsus', ru: 'Местное самоуправление', en: 'Local government' },
    created_at: '2025-01-20T09:00:00Z',
    geo: {
      district: 'Põhja-Tallinn',
      settlement: 'Tallinn',
      region: 'Harju maakond',
      country: 'Eesti',
      lat: 59.45,
      lon: 24.7,
    },
  },
  {
    id: 'DE-004',
    status: ISSUE_STATUS.NEW,
    type: ISSUE_TYPE.INCIDENT,
    labels: ['infrastructure'],
    title: { et: 'Imetehnilised süsteemid maksmiste jaoks', ru: 'Устаревшие системы выплат', en: 'Outdated payment systems' },
    summary: { et: 'IT-süsteemid pensionide ja toetuste maksmiseks on vananenud. Palun avalik moderniseerimisplaan.', ru: 'IT-системы для выплат пенсий и пособий устарели. Прошу публичную дорожную карту модернизации.', en: 'IT systems for pensions and benefit payments are outdated. Request for public modernisation roadmap.' },
    description: { et: 'Meedias kajastati vananenud IT-süsteemide kasutamist pensionide ja toetuste maksmiseks. Palun esitada avalik moderniseerimise teekond ja ligikaudsed uuendamise tähtajad.', ru: 'В СМИ сообщалось об использовании устаревших IT-систем для выплат пенсий и пособий. Прошу предоставить публичную дорожную карту модернизации этих систем и ориентировочные сроки обновления.', en: 'The media reported on the use of outdated IT systems for pensions and benefit payments. Please provide a public roadmap for modernising these systems and approximate update timelines.' },
    institution: { et: 'Riigi Infosüsteemi Amet', ru: 'Riigi Infosüsteemi Amet', en: 'Information System Authority' },
    created_at: '2025-01-22T11:15:00Z',
  },
  {
    id: 'DE-005',
    status: ISSUE_STATUS.PUBLISHED,
    type: ISSUE_TYPE.IMPROVEMENT,
    labels: ['safety', 'infrastructure'],
    title: { et: 'Koormus ja digitaalsed tööriistad', ru: 'Нагрузка и цифровые инструменты', en: 'Workload and digital tools' },
    summary: { et: 'Uued digivormid suurendasid administratiivset koormust medpersonalil.', ru: 'Новые цифровые формы увеличили административную нагрузку на медперсонал.', en: 'New digital reporting forms increased administrative burden on medical staff.' },
    description: { et: 'Uute digitaalsete aruandlusvormide kasutuselevõtt suurendas medpersonalile administratiivset koormust. Palun hinnata digitaalsete süsteemide mõju tegelikule patsientidega töötamise ajale.', ru: 'Внедрение новых цифровых форм отчётности увеличило административную нагрузку на медицинский персонал. Прошу оценить влияние цифровых систем на фактическое время работы с пациентами.', en: 'The introduction of new digital reporting forms increased the administrative burden on medical staff. Please assess the impact of digital systems on actual time spent with patients.' },
    institution: { et: 'Haigekassa', ru: 'Haigekassa', en: 'Health Insurance Fund' },
    created_at: '2025-01-25T16:45:00Z',
    geo: {
      district: 'Lasnamäe',
      settlement: 'Tallinn',
      region: 'Harju maakond',
      country: 'Eesti',
      postal_code: '13619',
      lat: 59.43,
      lon: 24.85,
    },
  },
  {
    id: 'DE-006',
    status: ISSUE_STATUS.NEW,
    type: ISSUE_TYPE.INCIDENT,
    labels: ['waste'],
    title: { et: 'Muutused tasudes ja aruandluses', ru: 'Изменение сборов', en: 'Changes in fees and reporting' },
    summary: { et: 'Admin tasud ja aruandlusnõuded muutuvad mitu korda aastas. Palun põhjendus ja prognoos.', ru: 'Админсборы и требования к отчётности меняются несколько раз в год. Прошу обоснование и прогноз.', en: 'Administrative fees and reporting requirements change several times a year. Request for justification and regulatory forecast.' },
    description: { et: 'Haldustasud ja aruandlusnõuded muutuvad mitu korda aastas. Palun avaldada muudatuste põhjendused ja väikese ettevõtluse regulatiivse koormuse prognoos.', ru: 'Административные сборы и требования к отчётности изменяются несколько раз в год. Прошу публиковать обоснование изменений и прогноз регуляторной нагрузки на малый бизнес.', en: 'Administrative fees and reporting requirements change several times a year. Please publish the rationale for changes and a forecast of regulatory burden on small business.' },
    institution: { et: 'Maksu- ja Tolliamet', ru: 'Maksu- ja Tolliamet', en: 'Tax and Customs Board' },
    created_at: '2025-01-28T08:30:00Z',
  },
  {
    id: 'DE-007',
    status: ISSUE_STATUS.NEW,
    type: ISSUE_TYPE.INCIDENT,
    labels: ['district', 'waste'],
    title: { et: 'Eluaseme kättesaadavus', ru: 'Доступность жилья', en: 'Housing affordability' },
    summary: { et: 'Üür üliõpilaselinnades on järsult tõusnud. Kas kaalutakse meetmeid?', ru: 'Аренда в студенческом секторе резко выросла. Рассматриваются ли меры?', en: 'Rent in the student sector has risen sharply. Are measures being considered?' },
    description: { et: 'Üliõpilaselinnade üürid on järsult tõusnud. Palun teavitada, kas kaalutakse meetmeid taskukohase eluaseme laiendamiseks üliõpilastele.', ru: 'В студенческом секторе резко выросла стоимость аренды. Прошу сообщить, рассматриваются ли меры по расширению доступного жилья для студентов.', en: 'Rent in the student housing sector has risen sharply. Please inform whether measures to expand affordable housing for students are being considered.' },
    institution: { et: 'Kohalik omavalitsus', ru: 'Местное самоуправление', en: 'Local government' },
    created_at: '2025-02-01T12:00:00Z',
  },
  {
    id: 'DE-008',
    status: ISSUE_STATUS.IN_REVIEW,
    type: ISSUE_TYPE.INCIDENT,
    labels: ['district'],
    title: { et: 'Pensioniea tõus', ru: 'Повышение пенсионного возраста', en: 'Pension age increase' },
    summary: { et: 'Palun isiklik arvutus oma pensioniaja ja summa kohta.', ru: 'Прошу персональный расчёт предполагаемой даты выхода и размера выплат.', en: 'Request for personal calculation of expected pension date and benefit amount.' },
    description: { et: 'Seoses pensioniea sidumisega elueaga palun esitada minu eeldatava pensionile jäämise kuupäeva ja oodatavate maksmiste suuruse isiklik arvutus.', ru: 'В связи с привязкой пенсионного возраста к продолжительности жизни прошу предоставить персональный расчёт моей предполагаемой даты выхода на пенсию и размер ожидаемых выплат.', en: 'In connection with the linking of pension age to life expectancy, please provide a personal calculation of my expected pension start date and amount of expected benefits.' },
    institution: { et: 'Sotsiaalkindlustusamet', ru: 'Sotsiaalkindlustusamet', en: 'Social Insurance Board' },
    created_at: '2025-02-03T10:00:00Z',
  },
  {
    id: 'DE-009',
    status: ISSUE_STATUS.PUBLISHED,
    type: ISSUE_TYPE.IMPROVEMENT,
    labels: ['waste', 'infrastructure'],
    title: { et: 'Protsesside dubleerimine', ru: 'Дублирование процессов', en: 'Process duplication' },
    summary: { et: 'Ametite vahel tuleb korduvalt esitada juba olemasolevaid andmeid.', ru: 'Между ведомствами требуется повторная подача уже имеющихся данных.', en: 'Agencies require resubmission of data already held in registries.' },
    description: { et: 'Ametite vahelisel suhtlemisel nõutakse andmete korduvalt esitamist, mis on juba riigi registrites olemas. Palun algatada infosüsteemide integreerimise analüüs.', ru: 'В рамках взаимодействия между ведомствами требуется повторная подача данных, уже имеющихся в государственных реестрах. Прошу инициировать анализ интеграции информационных систем.', en: 'When interacting between agencies, data already held in state registries must be resubmitted. Please initiate an analysis of information system integration.' },
    institution: { et: 'Siseministeerium', ru: 'Siseministeerium', en: 'Ministry of the Interior' },
    created_at: '2025-02-05T14:00:00Z',
  },
  {
    id: 'DE-010',
    status: ISSUE_STATUS.NEW,
    type: ISSUE_TYPE.INCIDENT,
    labels: ['waste', 'safety', 'infrastructure'],
    title: { et: 'Toetused ja protseduur', ru: 'Пособия и сложность процедуры', en: 'Benefits and procedure complexity' },
    summary: { et: 'Taotluse esitamine koosneb mitmest etapist ja nõuab isiklikku külastust.', ru: 'Подача заявления состоит из нескольких этапов и требует личного визита.', en: 'Application procedure has multiple steps and requires personal attendance.' },
    description: { et: 'Toetuse taotluse esitamise protseduur koosneb mitmest etapist ja nõuab isiklikku külastust. Palun tagada täielikult digitaalne alternatiiv ilma füüsilise kohalolekuta.', ru: 'Процедура подачи заявления на пособие состоит из нескольких этапов и требует личного визита. Прошу обеспечить полностью цифровую альтернативу без обязательного физического присутствия.', en: 'The benefit application procedure consists of several steps and requires a personal visit. Please provide a fully digital alternative without mandatory physical presence.' },
    institution: { et: 'Sotsiaalosakond', ru: 'Sotsiaalosakond', en: 'Social Welfare Department' },
    created_at: '2025-02-06T09:30:00Z',
  },
  {
    id: 'DE-011',
    status: ISSUE_STATUS.NEW,
    type: ISSUE_TYPE.INCIDENT,
    labels: ['district'],
    title: { et: 'Ühtne eksam', ru: 'Единый экзамен', en: 'Unified exam' },
    summary: { et: 'Üleminek eestikeelsele õppele mõjutas eksamite ettevalmistust. Kas vaja üleminekuperioodi?', ru: 'Переход на эстонский повлиял на подготовку к экзаменам. Нужен ли переходный период?', en: 'Transition to Estonian affected exam preparation. Is a transition period needed?' },
    description: { et: 'Üleminek eestikeelsele õppele mõjutas eksamite ettevalmistust. Palun hinnata vajadust üleminekuperioodi järele lõpetajate jaoks, kes õppisid muudetud programmi järgi.', ru: 'Переход на обучение на эстонском повлиял на подготовку к экзаменам. Прошу оценить необходимость переходного периода для выпускников, обучавшихся по изменённой программе.', en: 'The transition to Estonian-language education affected exam preparation. Please assess the need for a transition period for graduates who studied under the changed programme.' },
    institution: { et: 'Haridusministeerium', ru: 'Haridusministeerium', en: 'Ministry of Education' },
    created_at: '2025-02-07T11:00:00Z',
  },
  {
    id: 'DE-012',
    status: ISSUE_STATUS.PUBLISHED,
    type: ISSUE_TYPE.INCIDENT,
    labels: ['waste'],
    title: { et: 'Tagasiside avaldustele', ru: 'Обратная связь на обращения', en: 'Feedback on submissions' },
    summary: { et: 'Eelmistele avaldustele said vormilised vastused. Palun mehhanism avalduste staatuse jälgimiseks.', ru: 'На предыдущие обращения получены формальные ответы. Прошу механизм отслеживания статуса.', en: 'Previous submissions received formal replies. Request for mechanism to track submission status.' },
    description: { et: 'Eelmistele avaldustele sain vormilised vastused ilma konkreetsete tegevuste märkimiseta. Palun rakendada avalduste staatuse jälgimise mehhanism koos läbipaistva töötlemise meetrikaga.', ru: 'На предыдущие обращения получены формальные ответы без указания конкретных действий. Прошу внедрить механизм отслеживания статуса обращений с прозрачной метрикой обработки.', en: 'Previous submissions received formal responses without specifying concrete actions. Please implement a mechanism to track submission status with a transparent processing metric.' },
    institution: { et: 'Riigikantselei', ru: 'Riigikantselei', en: 'Government Office' },
    created_at: '2025-02-08T15:20:00Z',
  },
  {
    id: 'DE-013',
    status: ISSUE_STATUS.NEW,
    type: ISSUE_TYPE.INCIDENT,
    labels: ['waste'],
    title: {
      et: 'Inglisekeelne pealkiri puudub',
      ru: 'Английский заголовок отсутствует',
    },
    summary: {
      et: 'Demonstreerib fallback-märki, kui UI keel puudub väljal.',
      ru: 'Демонстрирует маркер fallback при отсутствии локали в поле.',
      en: 'Demonstrates fallback marker when UI locale is missing on field.',
    },
    description: {
      et: 'See issue on mõeldud fallback-märgi näitamiseks FAKE-OLD režiimis: pealkirjal pole ingliskeelset varianti.',
      ru: 'Это обращение для демонстрации маркера fallback в FAKE-OLD: у заголовка нет английской локали.',
      en: 'This issue demonstrates the content fallback marker in FAKE-OLD: title has no English locale.',
    },
    institution: { et: 'Riigikantselei', ru: 'Правительственная канцелярия' },
    original_locale: ['et', 'ru', 'en'],
    created_at: '2025-02-09T10:00:00Z',
  },
])

export function findDemoIssueById(id) {
  return ROUTING_DEMO_ISSUES.find((item) => item.id === id) ?? null
}
